[build]
  command = "echo //npm.pkg.github.com/:_authToken=${PERSONAL_ACCESS_TOKEN} >> .npmrc && echo 'always-auth=true' >> .npmrc && yarn && yarn build"

[[redirects]]

from = "/*"
to = "/"
status = 200