name: Drive Web CI
on:
  push:
    branches: [master, DW20BT-50]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'

      - run: echo "registry=https://registry.yarnpkg.com/" > .npmrc
      - run: echo "@internxt:registry=https://npm.pkg.github.com" >> .npmrc
      # You cannot read packages from other private repos with GITHUB_TOKEN
      # You have to use a PAT instead https://github.com/actions/setup-node/issues/49
      - run: echo //npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_ACCESS_TOKEN}} >> .npmrc
      - run: echo "always-auth=true" >> .npmrc
      - run: yarn
      # - run: yarn run test
      #   env:
      #     CI: true
      - name: Build
        run: yarn build
      - name: Install netlify
        run: npm install -g netlify
      - name: Deploy build
        env: 
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PAT }}
        run: DEBUG=* netlify deploy --dir=build